### ISSUE TITLE
Fasta line is too long (> 9998 chars)

### ISSUE THREAD

**Issue by mictadlo** [HingeAssembler/HINGE#109]
Hi,
I just clone a fresh HINGE code. Unfortunately, I got `Fasta line is too long (> 9998 chars)` by using `find /All_RawData/Each_Cell_Raw/ -name "*.fasta" | xargs -I {} fasta2DB banana {}`. This seems only to happen with PacBio Sequel data.

How is it possible to fix it?

Thank you in advance.

Michal

**Comment by govinda-kamath** [comment]
Please run

```
hinge correct-head <input-fasta> <output-fasta> <read-id-map>.txt
```

**Comment by mictadlo** [comment]
Your command fixed it.
