### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by 0xAF1F** [HingeAssembler/HINGE#113]
Aside from just finalizing the Debian package, I'm looking to run hinge on a set of bacterial genomes. I was wondering when you plan to cut a new release (the latest one shows as from September 2016).

Thanks for your consideration :)

**Comment by govinda-kamath** [comment]
We've just tagged a new release. We will release binaries for a few distributions soon.

**Comment by 0xAF1F** [comment]
Great! Thank you.
I'll be building from source for Debian and then use that for my analyses.
