### ISSUE TITLE
Question regarding clipping

### ISSUE THREAD

**Issue by ebioman** [HingeAssembler/HINGE#115]
Hi
I have a question regarding the work-flow. The minimal example from your **Running** section succeeds for me. But if I try with a subset from my data I cant get beyond the **clip** section. 
Upon running 

<pre><code>
Jun  5 09:36 edges.g_out.txt
dgmserv01.vital-it.ch HINGE_00000F hinge clip test.edges.hinges test.hinge.list whatever

Traceback (most recent call last):
  File "/software/UHTS/Assembler/HINGE/20170509/bin/../lib/hinge/pruning_and_clipping.py", line 1357, in <module>
    add_chimera_flags(G,prefix)
  File "/software/UHTS/Assembler/HINGE/20170509/bin/../lib/hinge/pruning_and_clipping.py", line 1054, in add_chimera_flags
    with open(cov_flags,'r') as f:
IOError: [Errno 2] No such file or directory: 'test.cov.flag'
</code></pre>

I guess I have 2 questions related to this

 1. is the ``identifier-of-run`` as you put it in the example just a random one which I can choose or should it relate to something from earlier steps in the pipeline?

 2. Indeed the mentioned file ``test.cov.flag`` does not exist. At which step should it have been created and what can be the source of it being missing?

I forgot to add, that if I am checking the demo of the ecoli P4, I find a file ``ecoli.cov.flag`` which seems to be generated in the first step of filtering, but it is empty. 

And indeed I have another file with the extension ``*.cov.flag`` in my folder as well but this one corresponds to the hinge layout step ``-o `` parameter. If I set though the  ``identifier-of-run`` similar to the ``-o`` parameter it suddenly refers to yet another file...

**Comment by ilanshom** [comment]
The `identifier-of-run` doesn't need to be related to any earlier step in the pipeline. It will just be a suffix added to the output files of the clip step.

The .cov.flag file is created in the filter step, and it uses the `-x` argument for its name. Was that different from `test` in your case? Also, can you tell us what happens if you create an empty file test.cov.flag and run clip?

**Comment by ebioman** [comment]
I restarted now the entire hinge steps again from the beginning and gave both, the ``identifier-of-run`` and the prefix ``-x`` and ``-o`` from layout the same name. Everything worked well. If I used another prefix though it always failed to find the correctly associated file.

**Comment by ilanshom** [comment]
That's good to know, thanks. In the next release of HINGE we will make some changes to prevent this confusion from happening.
