### ISSUE TITLE
DAMASKER and DASCRUBBER integration

### ISSUE THREAD

**Issue by mictadlo** [HingeAssembler/HINGE#117]
Hi,
Do you have any examples how it would be possible to integrate [DAMASKER](https://dazzlerblog.wordpress.com/command-guides/damasker-commands/) and [DASCRUBBER](https://dazzlerblog.wordpress.com/command-guides/dascrubber-command-guide/)?

Thank you in advance.

Michal

**Comment by govinda-kamath** [comment]
[This](https://github.com/HingeAssembler/HINGE/blob/master/demo/ecoli_P4_demo/run.sh) provides an example of using DASCRUBBER. 

You would need to set the 
```
[filter]
use_qv = true;
```
in the `filter` part of the `.ini` file you pass in as well. 

We do not use DAMASKER as we do attempt to resolve all repeats that are resolvable from the data.
