### ISSUE TITLE
error at draft assembly stage

### ISSUE THREAD

**Issue by madhubioinfo** [HingeAssembler/HINGE#124]
Iam trying to run HINGE on my pacbio dataset , when am running draft-path, am getting the following error
    from pbcore.io import FastaIO
ModuleNotFoundError: No module named 'pbcore'

I tried installing by looking at this page https://github.com/PacificBiosciences/pbcore/issues/9
still the HINGE assembler is giving me the same error, please help me to solve this issue

**Comment by fxia22** [comment]
Thanks for reporting. What will happen if you run python and run `from pbcore.io import FastaIO`? You can verify pbcore is installed properly.

**Comment by fxia22** [comment]
btw, are you using python3 or python2.7?

**Comment by govinda-kamath** [comment]
Were you able to sort this out @madhubioinfo ?

**Comment by madhubioinfo** [comment]
sorry I couldn't get back to this issue , it was due to version of python and thanks for addressing my issue

**Comment by fxia22** [comment]
Thanks for your feedback.

**Comment by mictadlo** [comment]
Hi, I installed Hinge as described but it has failed with `ImportError: No module named pbcore.io` it seems that the library is missing:

```
> source utils/setup.sh
> python
Python 2.7.13 (default, Jul 21 2017, 16:25:46) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pbcore.io import FastaIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pbcore.io
>>> 
```
What did I miss?

Thank you in advance

MIchal

**Comment by govinda-kamath** [comment]
HI Mlchal,

You need to install [pbcore](https://pypi.python.org/pypi/pbcore/1.2.10). You can do it using `pip`. I've  updated the reqs.

**Comment by govinda-kamath** [comment]
You can also install by using `pip install -r requirements.txt `
using [this](https://github.com/HingeAssembler/HINGE-analyses/blob/master/requirements.txt) as `requirements.txt`.

**Comment by mictadlo** [comment]
Thank you, it works now. it would be good to have that file also in this repository.
