### ISSUE TITLE
Is it necessary to merge all .las file?

### ISSUE THREAD

**Issue by nottwy** [HingeAssembler/HINGE#130]
I find that you can use --mlas parameters to avoid load all .las file into memory.  It does work!

But I find that I have to merge all .las file. I want to know is it a necessary operaion and can I avoid merge all .las file?

**Comment by fxia22** [comment]
You don't have to merge all `.las` files, currently the whole pipeline can work on a block by block basis So you only need to pass `--mlas` flag and input file prefix `abc` and it will look for `abs.[numbers].las` files.

**Comment by nottwy** [comment]
But in this issue 'https://github.com/HingeAssembler/HINGE/issues/77', the command of 'draft' step is like this:
hinge draft --db yeast --las yeast.las --prefix yeast --config nominal.ini --out yeast.draft
How to explain this?

**Comment by fxia22** [comment]
In current version, you can do this instead:

`hinge draft --db yeast --las yeast --mlas --prefix yeast --config nominal.ini --out yeast.draft`

We will update the manual soon.

**Comment by nottwy** [comment]
Not only this step, I notice that the DASqv command also needs to be modified.
Now it's like this:
DASqv -c100 yeast yeast.las
But what should I do if I don't have a merged .las file?

**Comment by fxia22** [comment]
@nottwy you can now use `DASqv -c100 yeast yeast.*.las`

**Comment by nottwy** [comment]
Although the 'hinge layout'  step supports the --mlas option, it used up to 2 T memory.
Is it strange?

**Comment by govinda-kamath** [comment]
Can you give the exact command you used, and size of your las files?

**Comment by nottwy** [comment]
1.my command is:
hinge layout --db $db --las $las --mlas -x ${prefix} --config $cfg -o xyz
2.I have 95 las files with an average size 8.5G per file.
3.The version of my hinge is:
commit aa735993eb737f25b9c442dd71d0889b6ed35e09
Merge: 825432a a9e8582
Author: Fei Xia <xf1280@gmail.com>
Date:   Fri Sep 8 13:01:11 2017 -0700

    Merge pull request #128 from jameslz/patch-1
    
    add  Boost_INCLUDE_DIR
