### ISSUE TITLE
montonic versions

### ISSUE THREAD

**Issue by 0xaf1f** [HingeAssembler/HINGE#134]
Versions don't sort exactly mathematically, which is how you've been tagging them.

For example, 0.5 < 0.42 with version sorting (because each delimited number is evaluated separately and 42 > 5). You're probably looking to do something like 0.4.2, which would then sort appropriately behind 0.5. The way you're currently doing things affects our version watcher since it's currently picking up 0.42 as the latest version.

To avoid messing with previous tags, I'd suggest making all future 0.x releases two digits so that they continue to be seen as the biggest. Instead of 0.5, have 0.50, then 0.5y, then 0.60, and so on until you get to 1.0.

Thanks for your consideration!

**Comment by fxia22** [comment]
Version numbers are updated, now they are 3 digits. Thanks for your suggestions.
