### ISSUE TITLE
The 'postprocessing' step is too slow.

### ISSUE THREAD

**Issue by nottwy** [HingeAssembler/HINGE#137]
Dear developers,

Now I'm at the 'postprocessing' step. The command is presented below. But it takes too much time.

-----------------------

Run postprocessing
hinge clip ecoli.edges.hinges ecoli.hinge.list <identifier-of-run>

-----------------------
My data size is: 855 Gb .las file. Do you have any suggestions?

**Comment by ilanshom** [comment]
Hi @nottwy,

The `hinge clip` step doesn't use the .las files, it only uses the `.edges.hinges` and the `hinge.list` files. How big are those files for you? 

Typically this step is fast compared to the rest of the pipeline, so I'm surprised that it's taking that long. Is there any output to the console?

**Comment by govinda-kamath** [comment]
Also could you share `ecoli.edges.hinges` and  `ecoli.hinge.list` with us? This contains no sequence information (in case that's a concern for you).

**Comment by nottwy** [comment]
The size of edges.hinges is 113 M and of hinge.list is 27 M.

**Comment by ilanshom** [comment]
These are very large edge/hinges files. Does your genome have telomeres/centromeres? I suspect that the graph could be very dense in these repetitive parts. Do you have `del_telomeres = 1;` in your nominal.ini? 

Also, I remember that a while back you were trying to use the devG3 branch (see #129). Were you able to use it? Setting `aggressive_pruning = true` in your nominal.ini could also help.

**Comment by nottwy** [comment]
yeah, I still remember this thing and plan to do it. But now I just want to run your software successfully at this time. I'll give you response if I have any progress.

**Comment by nottwy** [comment]
Now it took me ~20  days at this step. Can you please make a little change to this step ('postprocessing') which makes the program reports the progress?

**Comment by ilanshom** [comment]
Yes, we can do that. But I think it would be helpful if we could have your edges.hinge and hinges.list files. Could you write an email to ilanshom@gmail.com, so that we can coordinate a way for you to send us the files? Thanks!

**Comment by nottwy** [comment]
@ilanshom ,
Have you received my email? Wait for your reply!

**Comment by ilanshom** [comment]
Yes, thank you. We got your files and are working on it. Sorry for the delay. We'll keep you posted.

**Comment by ilanshom** [comment]
Hi @nottwy,
We made some changes to `hinge clip` and it now scales to large datasets well. We were able to run it on the files you sent us in under 1 hour. Could you please checkout the latest commit, and try it again? Also, we now write many status messages so that you can tell us how far it went in case it gets stuck.

**Comment by nottwy** [comment]
I saw your reply yesterday. It's great. I'll try it soon and give you a reply.
The last task has run for > 30 days. Now I think it's time to kill it. ; )

**Comment by nottwy** [comment]
now I start to deal with this issue. I have other issues to deal with.
If there is any progress I will update this issue immediately.

**Comment by nottwy** [comment]
Only the information about reading is output:
[clip] Started hinge clip (09:20:46)
[clip] Reading xx.edges.hinges: 354699/354699
[clip] Graph with 764582 nodes built (09:21:16)
[clip] Reading xx.edges.hinges: 1661700/1661700

How about the progress of the date processing?
And I notice the clip runs with one thread. Can it be boosted with multi threads?

**Comment by nottwy** [comment]
Great Work!
Now it takes only 3 hours to finish the clip step.
