### ISSUE TITLE
DASqv

### ISSUE THREAD

**Issue by mictadlo** [HingeAssembler/HINGE#143]
Hi, is it enough to run only `DASqv ` command or do I have to run all other commands from dascrubber package?

Thank you in advance

Michal

**Comment by govinda-kamath** [comment]
`DASqv` is all we use. We use it to filter out chimeric reads. You could also run it without DASqv by setting `use_qv = false` in the `.ini` file you pass in.

**Comment by mictadlo** [comment]
did use catrack command to add it to the database?

**Comment by govinda-kamath** [comment]
No we don't. We act on the `.qual` directly.
