### ISSUE TITLE
Update about the project

### ISSUE THREAD

**Issue by alimayy** [HingeAssembler/HINGE#155]
Hi all,

Could you provide the HINGE community with a quick update about the plans for the future of this project? I see that the development practically stopped, which suggest that perhaps the latest developments in the field of long-read sequencing are not/will not be incorporated in the pipeline. 

Perhaps another, more personal point, is that for (commercial) companies like the one I work for, it is quite difficult to continue using (academic) software that is not under active development for several reasons. Concerns about support, stability and customer-friendliness are common with software that's not actively developed. 

Recently we've started a very extensive 'complete bacterial assembly' R&D project at BaseClear and regretfully I had to leave HINGE out of the competing methods as it's not under active development. 

Anyway, it would be great if you could leave a quick note on this. Thanks a lot in advance,

Ali

**Comment by ilanshom** [comment]
Hi Ali,

My apologies for the delay in responding. All three developers of HINGE are going through transition times in our careers, making it difficult for any one of us to maintain it. It may take a while until we can go back to actively updating and maintaining it. I will let you know if this changes.

Thanks for all your support (and understanding).

**Comment by alimayy** [comment]
Hi Ilan,

Thanks a lot for your answer. That's what I thought was happening (transitions). I wish you all success and in case interested the opportunity to get back to the long-read field which is always advancing and gaining wide popularity in microbial genomics. 

I'll keep an eye open then!
Ali
